version: "3.9"

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "127.0.0.1:35729:35729"
    volumes:
      - .:/site
      - jekyll-gems:/usr/local/bundle
    environment:
      JEKYLL_ENV: development

volumes:
  jekyll-gems:
